import type { Metadata } from 'next';
import { Oswald, Geist_Mono } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';

const oswald = Oswald({
  subsets: ['latin'],
  // Optional: customize weights
  // weight: ['200', '300', '400', '500', '600', '700'],
  // Optional: use display swap for better performance
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.className} antialiased`}>{children}</body>
    </html>
  );
}
